---
title: "Untitled"
output: html_document
date: "2023-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cdlTools)
```

```{r}
data <- read_csv("usa_00017.csv")
```

```{r}
set.seed(542)
data <- sample_n(data, 300000)
```

Data Filtering
```{r}
data$SEX <- as.factor(ifelse(data$SEX == 1, "Male", "Female")) # getting sex into character variable

data <- data[which(data$AGE >= 18), ] # getting only people above the age of 18
```


```{r}
# getting marital status for each individual into simplified variables
data$MARST <- as.factor(ifelse(data$MARST == 1 | data$MARST == 2, "Married",
  ifelse(data$MARST %in% c(3, 4, 5), "No Longer Married", "Single")
))

# getting census region of each individual
data$REGION <- as.factor(ifelse(data$REGION == 11, "New England Division",
  ifelse(data$REGION == 12, "Middle Atlantic Division",
    ifelse(data$REGION == 13, "Mixed Northeast Divisions (1970 Metro)",
      ifelse(data$REGION == 21, "East North Central Div.",
        ifelse(data$REGION == 22, "West North Central Div.",
          ifelse(data$REGION == 23, "Mixed Midwest Divisions (1970 Metro)",
            ifelse(data$REGION == 31, "South Atlantic Division",
              ifelse(data$REGION == 32, "East South Central Div.",
                ifelse(data$REGION == 33, "West South Central Div.",
                  ifelse(data$REGION == 34, "Mixed Southern Divisions (1970 Metro)",
                    ifelse(data$REGION == 41, "Mountain Division",
                      ifelse(data$REGION == 42, "Pacific Division", NA)
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
))

data$STATEFIP <- as.factor(fips(data$STATEFIP, to = "Abbreviation"))

data$METRO <- as.factor(ifelse(data$METRO == 0, NA,
  ifelse(data$METRO == 1, "Not in City", "In City")
))

data$RACE <- as.factor(ifelse(data$RACE == 1, "White",
  ifelse(data$RACE == 2, "Black",
    ifelse(data$RACE == 3, "Native American",
      ifelse(data$RACE %in% c(4, 5, 6), "Asian", "Other")
    )
  )
))

data$CITIZEN <- as.factor(ifelse(data$CITIZEN == 0, "Citizen",
  ifelse(data$CITIZEN %in% c(1, 2), "Citizen", "Non-Citizen")
))

data$EDUCD <- factor(
  ifelse(data$EDUCD %in% c(0, 1, 999), NA,
    ifelse(data$EDUCD %in% c(2:61), "No Highschool",
      ifelse(data$EDUCD %in% c(62:64), "High School",
        ifelse(data$EDUCD %in% c(65:80, 90:100, 110:113), "Some College",
          ifelse(data$EDUCD %in% c(81:83), "Associate's",
            ifelse(data$EDUCD == 101, "Bachelor's", "Graduate Degree")
          )
        )
      )
    )
  ),
  levels = c("No Highschool", "High School", "Some College", "Associate's", "Bachelor's", "Graduate Degree"),
  ordered = T
)
data$EMPSTAT <- as.factor(ifelse(data$EMPSTAT == 0, NA,
  ifelse(data$EMPSTAT == 1, "Employed",
    ifelse(data$EMPSTAT == 2, "Unemployed", "Not in Labor Force")
  )
))
```

```{r}
data <- data[c("REGION", "STATEFIP", "METRO", "FAMSIZE", "SEX", "AGE", "MARST", "RACE", "CITIZEN", "EDUCD", "EMPSTAT", "UHRSWORK", "INCWAGE")]
```

```{r}
#apply(data, function(x) sum(is.na(x)))
data <- data[!is.na(data$METRO),]
```


```{r}
save(data, file = "project542data.Rdata")
```
